export const ADD_TO_CART = 'ADD_TO_CART';
export const UPDATE_CART = 'UPDATE_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const SHOW_CART = 'SHOW_CART';

export const ADD_PRODUCTS = 'ADD_PRODUCTS'
export const ADD_PRODUCTS_CURRENCIES = 'ADD_PRODUCTS_CURRENCIES'
export const ADD_ACTIVE_CURRENCY = 'ADD_ACTIVE_CURRENCY'